# Rails 7 GTCX Backend API
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 2.7.0'

# Core gems
gem 'rails', '~> 7.0.0'
gem 'sqlite3'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false

# Authentication & Security
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'

# API gems
gem 'jsonapi-serializer'
gem 'api-pagination'
gem 'rack-attack'

# Ghana Government Integration
gem 'httparty'
gem 'faraday'

# Background Jobs
gem 'sidekiq'
gem 'redis'

# Storage & File Processing
gem 'aws-sdk-s3'
gem 'image_processing', '~> 1.2'

# Development & Testing
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end

# Production
group :production do
  gem 'lograge'
end